apiVersion: v1
kind: Service
metadata:
  name: log-analysis-dashboard-service
spec:
  selector:
    app: log-analysis-dashboard # This must match the labels in your Deployment
  ports:
    - protocol: TCP
      port: 80 # Port exposed externally by the LoadBalancer
      targetPort: 8050 # Port your application container is listening on
  type: LoadBalancer
